### PR TITLE
Fixed typo in French 'Dos' poster

### PR DESCRIPTION
**Pull request by sdussaut**
Changed 'quelques' to 'quelles que' in second paragraph.

### CODE REVIEW

**Comment by htmlzengarden** [comment]
Merci pour le coup de main Sébastien. J‘ai corrigé également dans une pull-request plus globale (https://github.com/UKHomeOffice/posters/pull/16).

**Comment by karypun** [comment]
@sdussaut please can you resolve the conflicts in the files?

**Comment by sdussaut** [comment]
@htmlzengarden Is this PR still needed? If not it can be closed I guess :-)

**Comment by htmlzengarden** [comment]
This is corrected yes, thank you again.

**Pull request closed without merging**
