### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ilianM**
Complete German translation of the posters

@guntbert We needed the posters for an event today, thats why we created a complete translation. Maybe you could have a look on our version.

### CODE REVIEW

**Comment by guntbert** [comment]
Great you made the whole thing  
Some personal remarks
- I like the polite "Bitte...", "Vermeide..." better than "Richtig", "Falsch"
- The wording of the guidelines in my version is more personal (like I read it in the English version too), whereas your version sounds like a somewhat impersonal command

just as an example

your version

> Richtig:  Alle Informationen auf Webseiten veröffentlichen  
> Falsch: Informationen in Downloads verstecken

-----------
my version  
>Bitte publiziere alle Informationen auf Webseiten  
>Vermeide, Informationen in Downloads zu verstecken

------------

In my eyes we are talking to technical oriented persons - so keeping words like "Design", "Layout" seems ok.

**Comment by guntbert** [comment]
I found a few typos
- in cover-back: s/Eischränk/Einschränk/
- in low-vision: s/verbvermitteln/vermitteln/
- in autistic-spectrum: s/Buttun/Button/

and one additional suggestion
- in cover-back: I'd prefer "für jeden bereitzustellen" statt " für jeden zu machen"

**Comment by ilianM** [comment]
We spent some time before we decided on using "Richtig", "Falsch". We wanted to have clear signal words in the column headings. As we showed the posters to some test candidates words like "Gut" und "Schlecht" or "Richtig", "Falsch" were more clear than "Bitte" and "Vermeide". Personally I would prefer something in between my and you solution, but couldn't finde better words.

As for the more impersonal commad we were in a conflict: as we address our clients / participants formally with "Sie", we needed formal language. The impresonal solution promised to work formal as well as informal.

I fixed all typos.

**Comment by guntbert** [comment]
Your arguments are very convincing - asking users is definitely better than relying just on personal preferences.

**Comment by ilianM** [comment]
@guntbert  Thanks for your support!

**Pull request merged**
