### PR TITLE
Translation posters into pt-BR

### PR DESCRIPTION
**Pull request by msales78**
Hello, I translated the posters into Brazilian Portuguese. It's my first pull request, so I do not know if I did something wrong or if I did everything right. Sorry if I missed something ... thanks for allowing everyone's contribution.

### CODE REVIEW

**Comment by karypun** [comment]
Hello @msales78, apologies for the delay. We need to review your pull request first. Will let you know when that's done. Thanks.

**Comment by msales78** [comment]
Thanks @karypun, no problem, i am available for any questions. :)

**Comment by karypun** [comment]
@msales78 Sorry for the delay in this. We had it reviewed and it's great. There were a few points made though, first one is quite important the second one is up to your discretion:

1. On covr-back_pt_BR.pdf: it says Home Office Digital, Data and Technology's .. tem o objetivo..  This is not a Portuguese one but should Technology's have the 's ? Shouldn't be Digital Data and Technology? as in the 's is supposed to sort of be the portuguese "tem" ? 

2a. on deaf_pt-BR: Not wrong either but it says : Projetando para usuários que são deficientes auditivos ou surdos. I think the "que são" is  superfluous. See this link from a Microsoft portuguese page for example: https://msdn.microsoft.com/pt-br/bb899566 it says only "Accessibilidade para usuários deficientes visuais" , the "que são" is not present. The difference in english would be "projecting for hearing impared users"  Vs "projecting for users that are hearing impared" .

2b. low-vision_pt-BR: same as above in the title.

Other than that is all mint :)

**Comment by msales78** [comment]
@karypun Thank you. No problems with the delay. The points make sense and I'll make the adjustments later this week. I'll send it next. Thanks.

**Pull request merged**
