### PR TITLE
Turkish Translate Added

### PR DESCRIPTION
**Pull request by lahmacun**
I Translated them to Turkish. Thanks for posters.

### CODE REVIEW

**Comment by karypun** [comment]
Thank you @efezahid for these translations and sorry for the delay in getting back to you. @cfq will be contacting you with some feedback. Hope that's ok as we've been doing lots of collaboration with the other translations :)

**Comment by ei8fdb** [comment]
ping @cfq.

**Comment by karypun** [comment]
@cfq I've added you as a collaborator to review these posters. Hope that's ok :)

**Comment by karypun** [comment]
Thank you @lahmacun

**Pull request merged**
