### PR TITLE
changes in spanish version: translation + grid

### PR DESCRIPTION
**Pull request by lopezbreit**
Hi!, loved this initiative & thanks for sharing.

This is what I changed in this _es version:

On the graphics:

- Created a grid providing a 3cm safety area and keeping all the graphic elements within an area of 10x10cm. It can be easier for the eye to scan and find its way through the piece.
- Removed vertical lines that divided the do/don´t columns as the left alignment of the elements already creates that division for the eye.
- Removed background from the main title trying to improve contrast and establishing a clearer point of entrance to the piece. 
- Changed the font weight to medium and 32px to fit the content easily.
- Created an .ai document for those who don´t have .sketch

On the spanish translation:

I´m Argentinian but tried to use a neutral spanish.

- Do-Don´t was translated as ¨yes¨ and ¨no¨ to favor the reading of the whole phrase.
- The equivalent to the metaphor ¨It´s raining cats and dogs¨ in spanish would be ¨esta lloviendo a cántaros¨ . I believe it isn´t that frequently used although most people in Spain and latin america would get it.

Hope more people joins and contributes!
thanks!
Tam

### CODE REVIEW

**Comment by karypun** [comment]
Hello @lopezbreit 
Thank you for your translations and supplying the .ai file. These are great :) 

Although I appreciate you removing the colour background in the main title to improve contrast, unfortunately, this kind of contrast- using pure white background against black text- can be problematic, especially for dyslexic users who may be sensitive to the brightness those high contrast colours cause. This can make the words swirl or blur together. An off-white, tan or softer colours in the background would work better.

The vertical line reinforces and makes the Dos and Don't columns much more clearer. We had early versions of these posters that were tested with some users and found they were overwhelmed by all the content and didn't know where to look.  We since reduced the number of advice on each poster and the vertical line made the differences more clearer.

Hope that helps? Where you've adjusted to the grid layout and using 'yes' or 'no' is perfectly acceptable as an alternative of 'do' and 'don't'.. and I like how you were able to use a metaphor that makes sense in Spanish as opposed to the cats and dogs 👍

**Comment by karypun** [comment]
Hi @lopezbreit 
Apologies for the delay as I'm out of the country now.
Before we can merge the pull request, can you make the changes mentioned above so they can be more accessible and we'll merge. Thanks! :)

**Comment by lopezbreit** [comment]
Hi @karypun,
Many thanks for the feedback! 
I was trying to upload them today but internet went down. I´d just committed them. You´ll find now a new version according to your comments. 
Best!,
Tam.

**Comment by karypun** [comment]
Thank you @lopezbreit 
They look great! :)

**Pull request merged**
