### PR TITLE
Added 4 more posters

### PR DESCRIPTION
**Pull request by pedrocs**
Translated the cover, back cover, deaf and hard of hearing, and dyslexia posters, to European Portuguese. Only three posters left to translate.

### CODE REVIEW

**Comment by pedrocs** [comment]
Hi @karypun thanks for the feedback, I will check and fix that missing e-mail!

**Comment by pedrocs** [comment]
Hi! Sorry, I've been traveling a bit. Just added those missing addresses, also unlocked the address layer in the autism poster, so I committed that as well.

**Comment by pedrocs** [comment]
I took the chance and also finished the remaining posters.

**Comment by karypun** [comment]
Thank you @pedrocs these look great!

**Comment by pedrocs** [comment]
Thanks! Glad to contribute.

**Pull request merged**
