### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by htmlzengarden**
Translation notes:

* Adjustments have been made on the illustrations. “It's raining cats and dogs” vs. “Il pleut des cordes” for example.
* The vocabulary and expressions used have been simplified to answer one of the recommendations of the document.

### CODE REVIEW

**Comment by juliemoynat** [comment]
Thankyou for these translations posters!

In "motor-disabilities_fr.pdf" I noticed some mistakes.
- For "réaliser des contenus dynamiques qui demandent de nombreuses intéractions", "intéractions" shouldn't have an accent : "interactions"
- "Votre session à expirée" should be "Votre session a expiré"

Then, for "mobile and touchscreen" part, I would have translate "ne pas oublier les téléphones portables et autres écrans tactiles lors de la conception" because there are not only smartphones with touchscreen (also tablets and computers).

**Comment by karypun** [comment]
@htmlzengarden We corrected the English version of the Deaf poster today. In the last point "Don't make telephone the only means of contact for users" we removed the word "Don't" because it's already implied on the top heading. Are you able to amend this? Thank you :)

**Comment by ei8fdb** [comment]
Thank you very much @htmlzengarden and @juliemoynat for your French translations.

I particularly like how you both worked together to come up with good French localisation. This is really what we hoped would happen.

Thanks very much. We will give you full credit on Twitter.

@juliemoynat have you got a twitter handle I can reference? Otherwise I'll reference your Github.

**Comment by juliemoynat** [comment]
Hi @ei8fdb, my Twitter account is @juliemoynat just like on Github ;-)

**Pull request merged**
