### PR TITLE
First try for a German translation

### PR DESCRIPTION
**Pull request by guntbert**
I don't have access to to Sketch so I used Libreoffice Draw for editing
the pdf.

I am confident about the wording I chose, but please have a look at the resulting pdf - I am not certain if what Draw generates is acceptable.

### CODE REVIEW

**Comment by karypun** [comment]
@guntbert If you download Fontawesome http://fontawesome.io/  this will help with the icons appear correctly in the posters.

**Comment by guntbert** [comment]
@karypun thank you, did you see any issues in my pdfs?

**Comment by ei8fdb** [comment]
Hi @guntbert, thanks for starting on German translations. Thats really helpful.

I think you're right Draw might not be up to the job to generate PDFs.

Can you tell us what applications you use so we can get you a file format that you can work with?

We're trying to identify the best (as in most cross platform, and open) file format to produce for everyone.

It'd be really great if we could discuss the German translations over in #12. 

What do you think?

**Comment by guntbert** [comment]
I realize that not editing the pdf but rather the svg-source is a much better way - So I close this PR.

**Pull request closed without merging**
